//
//  SearchDetailInteractor.swift
//  KakaoBank
//
//  Created by Yong Seok Kim on 2020/06/29.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchDetailBusinessLogic
{
  func doSomething(request: SearchDetail.Something.Request)
}

protocol SearchDetailDataStore {
  var selectedSearchData: SearchResultModel? { get set }
}

class SearchDetailInteractor: SearchDetailBusinessLogic, SearchDetailDataStore {
  var presenter: SearchDetailPresentationLogic?
  var worker: SearchDetailWorker?
  var selectedSearchData: SearchResultModel?
  
  // MARK: Do something
  
  func doSomething(request: SearchDetail.Something.Request)
  {
    worker = SearchDetailWorker()
    worker?.doSomeWork()
    
    let response = SearchDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
