//
//  SearchDetailPresenter.swift
//  KakaoBank
//
//  Created by Yong Seok Kim on 2020/06/29.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchDetailPresentationLogic
{
  func presentSomething(response: SearchDetail.Something.Response)
}

class SearchDetailPresenter: SearchDetailPresentationLogic
{
  weak var viewController: SearchDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchDetail.Something.Response)
  {
    let viewModel = SearchDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
