//
//  SearchMainPresenter.swift
//  KakaoBank
//
//  Created by Yong Seok Kim on 2020/06/28.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMainPresentationLogic {
    func present(response: SearchMain.Search.Response)
    func presentError()
}

class SearchMainPresenter: SearchMainPresentationLogic {
    weak var viewController: SearchMainDisplayLogic?
    
    // MARK: Do something
    
    func present(response: SearchMain.Search.Response) {
        viewController?.display(response: response)
    }
    
    func presentError() {
        
    }
}
