//
//  SearchMainInteractor.swift
//  KakaoBank
//
//  Created by Yong Seok Kim on 2020/06/28.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMainBusinessLogic
{
  func doSomething(request: SearchMain.Something.Request)
}

protocol SearchMainDataStore
{
  //var name: String { get set }
}

class SearchMainInteractor: SearchMainBusinessLogic, SearchMainDataStore
{
  var presenter: SearchMainPresentationLogic?
  var worker: SearchMainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchMain.Something.Request)
  {
    worker = SearchMainWorker()
    worker?.doSomeWork()
    
    let response = SearchMain.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
