//
//  SearchMainPresenter.swift
//  KakaoBank
//
//  Created by Yong Seok Kim on 2020/06/28.
//  Copyright (c) 2020 Yong Seok Kim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchMainPresentationLogic
{
  func presentSomething(response: SearchMain.Something.Response)
}

class SearchMainPresenter: SearchMainPresentationLogic
{
  weak var viewController: SearchMainDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchMain.Something.Response)
  {
    let viewModel = SearchMain.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
